version: '3'
services:
  nginx:
    container_name: my-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - web
    networks:
      - outer-network
      - inner-network

  mysql:
    container_name: my-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - data-network

  api:
    build: ./TodoListAPI
    working_dir: /app
    depends_on:
      - mysql
    networks:
      - inner-network
      - data-network

  web:
    build: ./web
    networks:
      - inner-network

volumes:
  db-data:

networks:
  inner-network:
  outer-network:
  data-network: